version: 0.2 
  
phases: 

  pre_build: 
    commands: 
    - echo Logging in to Amazon ECR.... 
    - aws --version
    # update the following line with your own region
    - $(aws ecr get-login --no-include-email --region us-east-1) 
  build: 
    commands: 
    - echo Build started on `date` 
    - echo Building the Docker image... 
    # update the following line with the name of your own ECR repository
    - docker build -t mydockerrepo . 
    # update the following line with the URI of your own ECR repository (view the Push Commands in the console)
    - docker docker tag mydockerrepo:latest 470119429744.dkr.ecr.us-east-1.amazonaws.com/mydockerrepo:latest
  post_build: 
    commands: 
    - echo Build completed on `date` 
    - echo pushing to repo
    # update the following line with the URI of your own ECR repository
    - docker push 470119429744.dkr.ecr.us-east-1.amazonaws.com/mydockerrepo:latest
#artifacts: 
    # - location 
    # - location 
  #discard-paths: yes 
  #base-directory: location 
#cache: 
  #paths: 
    # - paths 
 